spring.application.name=semana2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=${url-database}
spring.datasource.username=${user-database}
spring.datasource.password=${password-database}